insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('rhinos pantie''s Restaurant', '10:40', '8:55 PM', '915', '4th', 'New Westminster', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('lady''s circular Restaurant', '4:44', '9:11 PM', '0', 'Boyd', 'Burnaby', '44790-000');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('upshot knottier Restaurant', '3:08', '1:30 PM', '853', 'Dawn', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('cabbed belching Restaurant', '8:25', '5:14 PM', '10623', 'Sachs', 'New Westminster', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('skin''s karate''s Restaurant', '8:30', '7:42 PM', '1', 'Cherokee', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('ordeal homage''s Restaurant', '3:06', '11:26 PM', '01', 'Parkside', 'Surrey', '630008');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('deemed degrades Restaurant', '2:04', '7:44 PM', '4247', 'Schmedeman', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('aortae reclines Restaurant', '4:31', '3:22 PM', '060', 'Northport', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('claret previous Restaurant', '0:18', '7:10 PM', '16', 'Service', 'Coquitlam', '2732');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('racier huffiest Restaurant', '4:03', '1:03 PM', '4164', 'Anhalt', 'Burnaby', '9608');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('boldly biplanes Restaurant', '5:26', '1:42 PM', '13', 'Russell', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('gashes pioneers Restaurant', '3:07', '3:59 PM', '7', 'Welch', 'New Westminster', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('hoot''s tissue''s Restaurant', '7:21', '6:05 PM', '841', 'Lien', 'Coquitlam', '692380');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('cart''s grunting Restaurant', '3:23', '7:30 PM', '55299', 'Mallory', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('slut''s banishes Restaurant', '5:00', '9:36 PM', '04', 'Valley Edge', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('barter deluding Restaurant', '8:23', '1:56 PM', '21467', 'Autumn Leaf', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('ogle''s chillest Restaurant', '10:38', '4:24 PM', '92069', 'Burning Wood', 'Burnaby', '346781');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('fuss''s radiator Restaurant', '9:45', '9:31 PM', '3865', 'Springview', 'Coquitlam', '277-0883');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('gleans bellhops Restaurant', '0:15', '8:11 PM', '913', 'Bunting', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('valves colorful Restaurant', '6:44', '11:11 AM', '0449', 'Lawn', 'Surrey', '94209 CEDEX');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('vipers bluntest Restaurant', '0:45', '12:04 PM', '571', 'Talisman', 'New Westminster', '64130');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('buffed domain''s Restaurant', '7:23', '7:11 PM', '7', 'Bay', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('wakens outbound Restaurant', '5:03', '6:00 PM', '074', 'Gina', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('horn''s prenatal Restaurant', '7:31', '11:01 PM', '9', 'Commercial', 'Burnaby', '93691 CEDEX');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('hire''s politest Restaurant', '9:43', '5:54 PM', '64', 'Elgar', 'Coquitlam', '42704 CEDEX');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('brooch synopses Restaurant', '8:15', '2:49 PM', '9380', 'Morningstar', 'Burnaby', '8314');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('shirts studying Restaurant', '4:03', '11:35 AM', '5948', 'Mallory', 'New Westminster', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('felony criteria Restaurant', '8:32', '8:38 PM', '11830', 'Sherman', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('spaces warden''s Restaurant', '1:20', '6:47 PM', '8947', 'Cody', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('repair showered Restaurant', '7:03', '5:46 PM', '293', 'Briar Crest', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('parsec resorted Restaurant', '8:29', '12:08 PM', '1', 'Fordem', 'New Westminster', '44315');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('scheme pinnacle Restaurant', '4:17', '5:15 PM', '1', 'Hallows', 'New Westminster', '4925-577');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('lion''s cleanest Restaurant', '4:29', '7:56 PM', '1', 'Pepper Wood', 'New Westminster', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('arches brassier Restaurant', '2:38', '9:13 PM', '2', 'John Wall', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('luster ravished Restaurant', '9:55', '9:57 PM', '6579', 'Cottonwood', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('mood''s alleging Restaurant', '9:41', '10:50 PM', '0166', 'Anderson', 'Surrey', '627533');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('woulds freshest Restaurant', '3:25', '12:02 PM', '061', 'Messerschmidt', 'Surrey', '35513 CEDEX');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('raised weekends Restaurant', '10:44', '3:35 PM', '30', 'Gina', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('planks tomato''s Restaurant', '1:57', '9:46 PM', '37147', 'Redwing', 'Surrey', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('felled parented Restaurant', '5:02', '7:01 PM', '94850', 'Leroy', 'New Westminster', '72091 CEDEX 9');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('slacks wombat''s Restaurant', '3:24', '1:04 PM', '2', 'Holmberg', 'New Westminster', '0398');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('albino penciled Restaurant', '1:56', '11:44 AM', '453', 'Westport', 'Burnaby', '618703');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('danced pictures Restaurant', '2:52', '11:39 PM', '3748', 'Novick', 'Burnaby', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('jester abdicate Restaurant', '6:31', '7:50 PM', '93036', 'Grim', 'Burnaby', '4525-406');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('realms living''s Restaurant', '3:37', '5:20 PM', '61', 'Sunfield', 'New Westminster', '34-103');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('hovels mallards Restaurant', '7:14', '2:15 PM', '4', 'Kedzie', 'Burnaby', '36780');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('honied switched Restaurant', '9:18', '5:05 PM', '033', 'Packers', 'Coquitlam', null);
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('busted shrapnel Restaurant', '1:40', '8:15 PM', '3098', 'Anzinger', 'New Westminster', '28410');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('jackal weekdays Restaurant', '8:14', '9:26 PM', '4', 'Hoard', 'New Westminster', 'V6Z');
insert into Restaurant_table (Name, Start_Time, End_Time, Street_Num, Street, City, Postal_Code) values ('scolds humorous Restaurant', '1:52', '12:42 PM', '6268', 'Sycamore', 'Burnaby', '7210');
