insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (1, 'common reflex''s Restaurant', '6:07', '11:14 PM', 'Comanche', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (2, 'fitter bettor''s Restaurant', '10:34', '8:52 PM', 'Burning Wood', 'Surrey', '4607');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (3, 'global rental''s Restaurant', '4:44', '5:55 PM', 'Morning', 'Coquitlam', '8006');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (4, 'settle clutched Restaurant', '8:02', '6:39 PM', 'Waywood', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (5, 'grills barnyard Restaurant', '10:09', '2:13 PM', 'Montana', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (6, 'kiss''s spatting Restaurant', '6:28', '1:37 PM', 'Westerfield', 'Surrey', '2970-079');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (7, 'blog''s keystone Restaurant', '4:59', '1:19 PM', 'Bay', 'New Westminster', '06816');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (8, 'scrams subtlety Restaurant', '5:32', '4:40 PM', 'Westridge', 'Surrey', '59055 CEDEX 1');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (9, 'wicker cuttings Restaurant', '9:09', '11:40 AM', 'Derek', 'New Westminster', '4534');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (10, 'pander emitting Restaurant', '9:38', '7:38 PM', 'Atwood', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (11, 'champs assemble Restaurant', '0:05', '7:35 PM', 'Graceland', 'Surrey', '3004');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (12, 'porous stopping Restaurant', '0:51', '7:18 PM', 'Montana', 'New Westminster', '1030');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (13, 'pardon regattas Restaurant', '2:57', '11:15 AM', 'Marcy', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (14, 'ablest impended Restaurant', '3:45', '3:31 PM', 'Garrison', 'Coquitlam', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (15, 'harmed possible Restaurant', '0:15', '1:56 PM', 'Summerview', 'Coquitlam', '613603');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (16, 'darkly infringe Restaurant', '5:47', '7:02 PM', 'Troy', 'Burnaby', '7116');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (17, 'mildew molecule Restaurant', '2:43', '4:39 PM', 'Lerdahl', 'New Westminster', '21314');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (18, 'crabby uprising Restaurant', '1:43', '11:42 PM', 'Center', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (19, 'clawed released Restaurant', '7:01', '4:43 PM', 'Maple Wood', 'Coquitlam', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (20, 'crabby ornately Restaurant', '4:11', '12:08 PM', 'Hallows', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (21, 'stoney strike''s Restaurant', '0:32', '11:50 PM', '8th', 'Surrey', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (22, 'root''s unifying Restaurant', '10:52', '6:56 PM', 'Bashford', 'Coquitlam', '349 01');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (23, 'egging latitude Restaurant', '4:03', '11:43 AM', 'Oak Valley', 'Surrey', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (24, 'longed wiring''s Restaurant', '1:12', '7:17 PM', 'Randy', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (25, 'weasel cavity''s Restaurant', '9:17', '12:25 PM', 'Bluejay', 'Surrey', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (26, 'stowed tameness Restaurant', '2:00', '6:46 PM', 'Leroy', 'Burnaby', '3010');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (27, 'swiped calico''s Restaurant', '7:05', '4:09 PM', 'Golf', 'Burnaby', '11510');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (28, 'revoke amending Restaurant', '9:14', '6:59 PM', 'Barnett', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (29, 'client cubicles Restaurant', '10:38', '12:53 PM', 'Dennis', 'Surrey', '43800');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (30, 'medals snowball Restaurant', '4:27', '1:34 PM', 'Delaware', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (31, 'darned covetous Restaurant', '1:45', '10:16 PM', 'Kropf', 'New Westminster', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (32, 'kiln''s relief''s Restaurant', '6:29', '5:11 PM', '8th', 'Burnaby', '60201');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (33, 'dreams anecdota Restaurant', '0:37', '10:18 PM', 'Mariners Cove', 'Surrey', 'H4S');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (34, 'thongs accesses Restaurant', '10:42', '10:46 PM', 'Fisk', 'Coquitlam', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (35, 'scanty stiffing Restaurant', '6:44', '4:19 PM', 'Londonderry', 'Coquitlam', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (36, 'ruin''s bowlders Restaurant', '1:00', '9:04 PM', 'Ludington', 'Surrey', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (37, 'phases versions Restaurant', '5:48', '5:53 PM', 'Scofield', 'Burnaby', '9103');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (38, 'raster advocate Restaurant', '10:16', '6:00 PM', 'Warbler', 'Burnaby', null);
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (39, 'meat''s brisking Restaurant', '8:10', '12:21 PM', 'Cherokee', 'Surrey', '403567');
insert into Restaurant_table (RID, Name, Start_Time, End_Time, Street, City, Postal_Code) values (40, 'bone''s whetting Restaurant', '4:13', '10:46 PM', 'Russell', 'Coquitlam', '7329');